plugins {
    id("java")
    id('net.fabricmc.fabric-loom') version '1.15-SNAPSHOT'
    
    id("com.gradleup.shadow") version "9.4.0" apply false
    
    id("com.modrinth.minotaur") version "2.+" apply false
    id("net.darkhax.curseforgegradle") version "1.1.18" apply false
}

import net.darkhax.curseforgegradle.TaskPublishCurseForge

apply plugin: "java"
apply plugin: "com.gradleup.shadow"
apply plugin: "com.modrinth.minotaur"
apply from: "$rootDir/publishing.gradle"

String mod_version = "%s+%s".formatted(mod_base_version, mod_version_meta);

base.archivesName = archives_base_name
group = maven_group
version = mod_version

repositories {
    mavenLocal()
    mavenCentral()
    maven { url = 'https://maven.fabricmc.net/' }
    maven { url = 'https://maven.maxhenkel.de/repository/public' }
    maven {
        url = 'https://api.modrinth.com/maven'
        content {
            includeGroup "maven.modrinth"
        }
    }
}

loom {
    runs {
        client {
            client()
            runDir = "run/client"
            ideConfigGenerated = true
        }

        server {
            server()
            runDir = "run/server"
            ideConfigGenerated = true
        }
    }
}

runClient.doFirst {
    args = ['--username', "SVC-Dev.${new Random().nextInt(1000)}"]
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_dependency}"

    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"

    Set<String> apiModules = [
            'fabric-api-base',
            'fabric-command-api-v2',
            'fabric-lifecycle-events-v1'
    ]

    apiModules.forEach {
        include(implementation(fabricApi.module(it, fabric_api_version)))
    }

    implementation 'com.google.code.findbugs:jsr305:3.0.2'

    implementation "de.maxhenkel.configbuilder:configbuilder:${configbuilder_version}"
    shadow "de.maxhenkel.configbuilder:configbuilder:${configbuilder_version}"

    implementation "de.maxhenkel.voicechat:voicechat-api:${voicechat_api_version}"

    runtimeOnly "maven.modrinth:simple-voice-chat:fabric-${voicechat_mod_version}"
    runtimeOnly "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"

    implementation "javazoom:jlayer:${jlayer_version}"
    shadow "javazoom:jlayer:${jlayer_version}"
}

processResources {
    filteringCharset "UTF-8"

    HashMap modifiedSrc = new HashMap<>(project.properties)
    modifiedSrc.put("mod_version", mod_version)

    filesMatching("fabric.mod.json") {
        expand modifiedSrc
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = 'UTF-8'
    it.options.release = 25
}

java {
    withSourcesJar()
}

jar {
    from('LICENSE') {
        rename { "${it}_${archivesBaseName}" }
    }
}


tasks.register('curseforge', TaskPublishCurseForge) {
    group = "upload"
    description = "Publishes project to CurseForge"

    String mcVer = project.properties["minecraft_dependency"]
    String projectVer = project.properties["mod_version"]
    String projectId = project.properties["curseforge_project"]

    if(projectVer == null || projectVer.isBlank())
        throw new IllegalStateException("Project version should not be null when publishing.")

    apiToken = getCurseToken(project)

    var shouldPublish = project.properties["debug_publishing"]
    if(shouldPublish != null && shouldPublish.toString().equalsIgnoreCase("true"))
        debugMode = true

    def mainFile = upload(projectId, shadowJar)
    mainFile.displayName = "[FABRIC][${minecraft_dependency}] ${mod_title} ${mod_base_version}"
    mainFile.addModLoader("fabric")
    mainFile.addModLoader("quilt")
    mainFile.releaseType = project.properties["release_type"]

    mainFile.changelogType = "markdown"
    mainFile.changelog = new File(project.getRootDir(), "changelog.md")

    for(String version: getSupportedVersions(project.properties))
        mainFile.addGameVersion(version)

    mainFile.addRequirement("simple-voice-chat")

}

tasks.modrinth.configure({
    group = 'upload'
})
tasks.modrinthSyncBody.configure({
    group = 'upload'
})

modrinth {
    String[] versions = getSupportedVersions(project.properties);

    token = getModrinthToken(project)
    projectId = modrinth_id
    versionName = "[FABRIC][${minecraft_dependency}] ${mod_title} ${mod_base_version}"
    versionNumber = "${mod_version}"
    versionType = release_type.toUpperCase()
    uploadFile = shadowJar
    gameVersions = Arrays.asList(versions)
    loaders = ['fabric', 'quilt']

    syncBodyFrom = file('readme.md').text
    changelog = new File(project.getRootDir(), "changelog.md").readLines().join("\n")

    var shouldPublish = project.properties["debug_publishing"]
    if(shouldPublish != null && shouldPublish.toString().equalsIgnoreCase("true"))
        setDebugMode(true)

    dependencies {
        required.project '9eGKb6K1' // Simple Voice Chat
    }
}
tasks.modrinth.dependsOn(build)

shadowJar {
    configurations = [project.configurations.shadow]
    archiveClassifier = 'release'
    relocate 'de.maxhenkel.configbuilder', "de.maxhenkel.${mod_id}.configbuilder"
    relocate 'javazoom', "de.maxhenkel.${mod_id}.javazoom"
}